# Package

version       = "0.1.0"
author        = "prestosilver"
description   = "Autogenerated sanitized steamworks Binds"
license       = "MIT"
srcDir        = "src"

# Dependencies

requires "nim >= 2.2.0"
